<?php

namespace Database\Seeders;

use App\Models\Chef;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Review;
use Faker\Generator as Faker;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(Faker $faker): void
    {
        $chefs = Chef::all()->pluck('id');
        $reviews =
        [
            [
                'review_title' => "Pizza Margherita da sogno!",
                'review' => "La pizza Margherita che ho mangiato qui è stata una vera rivelazione. L'impasto era leggero e ben cotto, e il pomodoro fresco era semplicemente delizioso. La consiglio a tutti!",
                'user_name' => "PizzaLover99",
                'email' => "pizzalover99@example.com",
            ],
            [
                'review_title' => "Risotto ai funghi perfetto",
                'review' => "Ho provato il risotto ai funghi e sono rimasto estasiato. Era cremoso, ricco di sapore e i funghi erano freschi e ben cotti. Un piatto che rifarei volentieri!",
                'user_name' => "RisottoFan88",
                'email' => "risottofan88@example.com",
            ],
            [
                'review_title' => "Gelato artigianale incredibile",
                'review' => "Il gelato artigianale di questo ristorante è il migliore che abbia mai assaggiato. I gusti erano intensi e ben bilanciati. Assolutamente da provare!",
                'user_name' => "GelatoGuru77",
                'email' => "gelatoguru77@example.com",
            ],
            [
                'review_title' => "Tacos di pesce freschi e gustosi",
                'review' => "I tacos di pesce erano freschissimi e pieni di sapore! La combinazione di ingredienti era perfetta e il tutto era servito con una salsa piccante deliziosa. Tornerò sicuramente!",
                'user_name' => "TacoLover22",
                'email' => "tacolover22@example.com",
            ],
            [
                'review_title' => "Pasta al pesto sublime",
                'review' => "La pasta al pesto che ho assaggiato qui era davvero sublime. Il pesto era fatto in casa e aveva un sapore fresco e aromatico. Un piatto che consiglio vivamente!",
                'user_name' => "PastaFan33",
                'email' => "pastafan33@example.com",
            ],
            [
                'review_title' => "Insalata di quinoa mediocre",
                'review' => "Ho provato l'insalata di quinoa e non era niente di speciale. Gli ingredienti sembravano freschi, ma il sapore era piuttosto blando. Mi aspettavo di più.",
                'user_name' => "HealthyEater44",
                'email' => "healthyeater44@example.com",
            ],
            [
                'review_title' => "Hamburger senza infamia e senza lode",
                'review' => "L'hamburger che ho ordinato era buono, ma non eccezionale. La carne era cotta bene, ma il panino e i condimenti non si abbinavano perfettamente. Un pasto mediocre.",
                'user_name' => "BurgerFan55",
                'email' => "burgerfan55@example.com",
            ],
            [
                'review_title' => "Sushi deludente",
                'review' => "Ho provato il sushi e sono rimasto molto deluso. Il pesce non era fresco come speravo e il riso era troppo appiccicoso. Non tornerò per questo piatto.",
                'user_name' => "SushiCritic11",
                'email' => "sushicritic11@example.com",
            ],
            [
                'review_title' => "Pollo alla griglia asciutto",
                'review' => "Il pollo alla griglia era asciutto e privo di sapore. Anche i contorni non erano all'altezza. È stata un'esperienza culinaria piuttosto negativa.",
                'user_name' => "ChickenDisappointed99",
                'email' => "chickendisappointed99@example.com",
            ],
            [
                'review_title' => "Tiramisù troppo dolce",
                'review' => "Il tiramisù era eccessivamente dolce e non equilibrato. La crema copriva completamente il sapore del caffè. Purtroppo, non lo consiglio.",
                'user_name' => "DessertHater77",
                'email' => "desserthater77@example.com",
            ],[
                'review_title' => "Pasta troppo al dente",
                'review' => "La pasta era troppo al dente per i miei gusti. Non sono riuscito a gustarla come avrei voluto.",
                'user_name' => "PastaCritic22",
                'email' => "pastacritic22@example.com",
            ],
            [
                'review_title' => "Pizza poco cotta",
                'review' => "La pizza sembrava poco cotta al centro. L'impasto non era ben lievitato e non si sentiva croccante.",
                'user_name' => "PizzaLover99",
                'email' => "pizzalover99@example.com",
            ],
            [
                'review_title' => "Servizio lento",
                'review' => "Il cibo era buono, ma il servizio era incredibilmente lento. Ho dovuto aspettare più di 30 minuti per il primo piatto.",
                'user_name' => "ImpatientDiner",
                'email' => "impatientdiner@example.com",
            ],
            [
                'review_title' => "Troppo piccante",
                'review' => "Il piatto era talmente piccante che non riuscivo a gustare i sapori. Sarebbe utile avere una scala di piccantezza.",
                'user_name' => "SpicyNoMore",
                'email' => "spicynomore@example.com",
            ],
            [
                'review_title' => "Porzioni piccole",
                'review' => "Le porzioni erano davvero piccole, considerando il prezzo pagato. Mi aspettavo di più dal piatto principale.",
                'user_name' => "SmallPlateCritic",
                'email' => "smallplatecritic@example.com",
            ],
            [
                'review_title' => "Bevanda calda servita fredda",
                'review' => "Il mio cappuccino è stato servito tiepido e non caldo come mi aspettavo. Ha perso tutta la sua cremosità.",
                'user_name' => "CoffeeLover101",
                'email' => "coffeelover101@example.com",
            ],
            [
                'review_title' => "Ottimo antipasto, pessimo dessert",
                'review' => "Gli antipasti erano eccellenti, ma il dessert era insoddisfacente. La torta sembrava vecchia e secca.",
                'user_name' => "DessertDisaster",
                'email' => "dessertdisaster@example.com",
            ],
            [
                'review_title' => "Cibo troppo salato",
                'review' => "Ho trovato il cibo eccessivamente salato, soprattutto i contorni. Non ho potuto finire il piatto.",
                'user_name' => "SaltyTaste",
                'email' => "saltytaste@example.com",
            ],
            [
                'review_title' => "Ottima presentazione, gusto mediocre",
                'review' => "La presentazione del piatto era meravigliosa, ma purtroppo il sapore non era all'altezza dell'estetica.",
                'user_name' => "VisualEater",
                'email' => "visualeater@example.com",
            ],
            [
                'review_title' => "Cibo freddo",
                'review' => "Il cibo mi è arrivato freddo e ho dovuto chiedere di riscaldarlo. Deludente.",
                'user_name' => "ColdPlate",
                'email' => "coldplate@example.com",
            ],
            [
                'review_title' => "Pasta insipida",
                'review' => "La pasta non aveva sapore, sembrava bollita in acqua senza sale. Un piatto senza personalità.",
                'user_name' => "FlavorSeeker",
                'email' => "flavorseeker@example.com",
            ],
            [
                'review_title' => "Troppo costoso per la qualità",
                'review' => "Il prezzo del pasto non giustificava la qualità del cibo. Mi aspettavo molto di più per il costo.",
                'user_name' => "BudgetGourmet",
                'email' => "budgetgourmet@example.com",
            ],
            [
                'review_title' => "Esperienza culinaria deludente",
                'review' => "L'esperienza culinaria nel complesso è stata deludente. Il servizio e il cibo non erano all'altezza.",
                'user_name' => "CriticalTaster",
                'email' => "criticaltaster@example.com",
            ],
            [
                'review_title' => "Cameriere poco attento",
                'review' => "Il cameriere sembrava disinteressato e non ci ha mai chiesto se avevamo bisogno di qualcosa.",
                'user_name' => "ServiceMatters",
                'email' => "servicematters@example.com",
            ],
            [
                'review_title' => "Dessert troppo piccolo",
                'review' => "Il dessert era buono, ma la porzione era così piccola che non valeva la pena ordinarlo.",
                'user_name' => "SweetTooth",
                'email' => "sweettooth@example.com",
            ],
            [
                'review_title' => "Pane raffermo",
                'review' => "Il pane servito al tavolo era raffermo e duro. Un vero peccato, dato che il resto del pasto era accettabile.",
                'user_name' => "BreadLover",
                'email' => "breadlover@example.com",
            ],
            [
                'review_title' => "Sapore artificiale",
                'review' => "Alcuni ingredienti avevano un sapore artificiale, come se fossero stati usati aromi non naturali.",
                'user_name' => "NaturalOnly",
                'email' => "naturalonly@example.com",
            ],
            [
                'review_title' => "Troppo tempo di attesa",
                'review' => "Abbiamo dovuto aspettare più di un'ora per il nostro cibo. Anche se il locale era pieno, il tempo di attesa era inaccettabile.",
                'user_name' => "HungryCustomer",
                'email' => "hungrycustomer@example.com",
            ],
            [
                'review_title' => "Porzione troppo grande",
                'review' => "La porzione era così grande che non sono riuscito a finirla. Sarebbe meglio avere porzioni più bilanciate.",
                'user_name' => "BigPlateBlues",
                'email' => "bigplateblues@example.com",
            ],
            [
                'review_title' => "Troppo unto",
                'review' => "Il piatto era troppo unto e pesante. Avrei preferito qualcosa di più leggero.",
                'user_name' => "LightEater",
                'email' => "lighteater@example.com",
            ],
            [
                'review_title' => "Cibo eccellente!",
                'review' => "Il cibo era assolutamente delizioso e ben presentato. Ogni piatto era un capolavoro.",
                'user_name' => "FoodLover123",
                'email' => "foodlover123@example.com",
            ],
            [
                'review_title' => "Servizio impeccabile",
                'review' => "Il personale è stato cordiale e molto attento. Mi sono sentito coccolato durante tutta la cena.",
                'user_name' => "HappyDiner88",
                'email' => "happydiner88@example.com",
            ],
            [
                'review_title' => "Esperienza indimenticabile",
                'review' => "Dall'antipasto al dessert, tutto era perfetto. Tornerò sicuramente!",
                'user_name' => "GourmetTraveler",
                'email' => "gourmettraveler@example.com",
            ],
            [
                'review_title' => "Ambiente fantastico",
                'review' => "Il locale è accogliente e l'atmosfera rilassante. Il cibo non delude mai.",
                'user_name' => "AmbienceLover",
                'email' => "ambiencelover@example.com",
            ],
            [
                'review_title' => "Pizza da sogno",
                'review' => "La pizza era cotta alla perfezione. Croccante fuori e morbida dentro. Ottimo lavoro!",
                'user_name' => "PizzaFanatic",
                'email' => "pizzafanatic@example.com",
            ],
            [
                'review_title' => "Sapori autentici",
                'review' => "Finalmente un ristorante che rispetta la tradizione italiana con ingredienti freschi e genuini.",
                'user_name' => "AuthenticEater",
                'email' => "authenticeater@example.com",
            ],
            [
                'review_title' => "Dessert paradisiaco",
                'review' => "Il tiramisù era il migliore che abbia mai mangiato. Leggero, cremoso e perfetto.",
                'user_name' => "SweetTooth",
                'email' => "sweettooth@example.com",
            ],
            [
                'review_title' => "Ottima scelta di vini",
                'review' => "La selezione di vini è ampia e ben curata. Ogni piatto aveva l'abbinamento perfetto.",
                'user_name' => "WineLover",
                'email' => "winelover@example.com",
            ],
            [
                'review_title' => "Prezzo giusto per la qualità",
                'review' => "Nonostante il livello alto del cibo e del servizio, i prezzi erano assolutamente onesti.",
                'user_name' => "BudgetGourmet",
                'email' => "budgetgourmet@example.com",
            ],
            [
                'review_title' => "Perfetto per una serata romantica",
                'review' => "Il posto ideale per una cena intima. L'atmosfera era magica e il cibo sublime.",
                'user_name' => "RomanticDiner",
                'email' => "romanticdiner@example.com",
            ],
            [
                'review_title' => "Piatti creativi e deliziosi",
                'review' => "Ogni piatto era unico e sorprendente. L'attenzione ai dettagli è incredibile.",
                'user_name' => "CreativeChefFan",
                'email' => "creativecheffan@example.com",
            ],
            [
                'review_title' => "Porzioni abbondanti",
                'review' => "Non solo il cibo era buonissimo, ma anche le porzioni erano generose. Ho dovuto portarmi a casa gli avanzi!",
                'user_name' => "FullBelly",
                'email' => "fullbelly@example.com",
            ],
            [
                'review_title' => "Locale moderno e accogliente",
                'review' => "Un perfetto mix tra modernità e tradizione. Il locale è arredato con gusto e il cibo è eccezionale.",
                'user_name' => "DesignLover",
                'email' => "designlover@example.com",
            ],
            [
                'review_title' => "Cucina genuina",
                'review' => "Ingredienti freschi e saporiti. La cucina tradizionale italiana eseguita alla perfezione.",
                'user_name' => "FreshFoodFan",
                'email' => "freshfoodfan@example.com",
            ],
            [
                'review_title' => "Servizio rapido e cortese",
                'review' => "Nonostante il locale fosse pieno, il servizio è stato veloce e professionale.",
                'user_name' => "FastService",
                'email' => "fastservice@example.com",
            ],
            [
                'review_title' => "Qualità costante",
                'review' => "Ogni volta che vengo qui, la qualità del cibo e del servizio è sempre la stessa: eccellente.",
                'user_name' => "RegularCustomer",
                'email' => "regularcustomer@example.com",
            ],
            [
                'review_title' => "Il miglior ristorante della città",
                'review' => "Senza dubbio uno dei migliori posti in cui abbia mai mangiato. Continuate così!",
                'user_name' => "TopDiner",
                'email' => "topdiner@example.com",
            ],
            [
                'review_title' => "Atmosfera rilassante",
                'review' => "Un ambiente tranquillo e confortevole, perfetto per godersi una cena in pace.",
                'user_name' => "ChillVibes",
                'email' => "chillvibes@example.com",
            ],
            [
                'review_title' => "Cibo che parla da sé",
                'review' => "Non ci sono parole per descrivere quanto era buono tutto. Complimenti allo chef!",
                'user_name' => "NoWords",
                'email' => "nowords@example.com",
            ],
            [
                'review_title' => "Tutto perfetto",
                'review' => "Dal servizio al cibo, tutto era perfetto. Non vedo l'ora di tornare.",
                'user_name' => "PerfectionSeeker",
                'email' => "perfectionseeker@example.com",
            ],
            [
                'review_title' => "Carbonara spettacolare!",
                'review' => "La carbonara era perfetta, con la giusta cremosità e sapore di guanciale. Una delizia assoluta.",
                'user_name' => "CarbonaraKing",
                'email' => "carbonaraking@example.com",
            ],
            [
                'review_title' => "Gnocchi fatti a mano eccellenti",
                'review' => "Gli gnocchi erano soffici e leggeri, accompagnati da un sugo delizioso. Li consiglio vivamente!",
                'user_name' => "GnocchiLover",
                'email' => "gnocchilover@example.com",
            ],
            [
                'review_title' => "Grigliata mista perfetta",
                'review' => "La grigliata mista era cotta alla perfezione, con carne tenera e saporita. Tornerò sicuramente per un bis.",
                'user_name' => "MeatFanatic",
                'email' => "meatfanatic@example.com",
            ],
            [
                'review_title' => "Zuppa di pesce da provare",
                'review' => "La zuppa di pesce era ricca di sapore, con pesce fresco e ben cucinato. Un piatto eccellente.",
                'user_name' => "SeafoodLover",
                'email' => "seafoodlover@example.com",
            ],
            [
                'review_title' => "Cacio e pepe come tradizione vuole",
                'review' => "Un piatto semplice ma eseguito in modo impeccabile. Il cacio e pepe era cremoso e saporito al punto giusto.",
                'user_name' => "TraditionalTaster",
                'email' => "traditionaltaster@example.com",
            ],
            [
                'review_title' => "Crostata al limone spettacolare",
                'review' => "Il dessert è stato la ciliegina sulla torta. La crostata al limone era fresca e deliziosa.",
                'user_name' => "DessertLover",
                'email' => "dessertlover@example.com",
            ],
            [
                'review_title' => "Tagliata di manzo succosa",
                'review' => "La tagliata di manzo era cotta alla perfezione e succosa. Consiglio questo piatto agli amanti della carne.",
                'user_name' => "SteakLover",
                'email' => "steaklover@example.com",
            ],
            [
                'review_title' => "Servizio un po' distratto",
                'review' => "Il cibo era buono, ma il servizio lasciava a desiderare. Ho dovuto richiamare più volte il cameriere.",
                'user_name' => "ImpatientCustomer",
                'email' => "impatientcustomer@example.com",
            ],
            [
                'review_title' => "Ravioli di zucca fantastici",
                'review' => "I ravioli di zucca erano dolci e ben bilanciati. Un piatto che consiglio a chi ama i sapori autunnali.",
                'user_name' => "PumpkinFan",
                'email' => "pumpkinfan@example.com",
            ],
            [
                'review_title' => "Frittura di calamari leggera",
                'review' => "La frittura di calamari era leggera e croccante, senza risultare pesante. Perfetta!",
                'user_name' => "CalamariLover",
                'email' => "calamarilover@example.com",
            ],
            [
                'review_title' => "Dolci troppo zuccherati",
                'review' => "I dessert erano eccessivamente dolci per i miei gusti. Avrei preferito qualcosa di più equilibrato.",
                'user_name' => "LowSugar",
                'email' => "lowsugar@example.com",
            ],
            [
                'review_title' => "Spaghetti alle vongole deliziosi",
                'review' => "Gli spaghetti alle vongole erano semplicemente perfetti. Freschi e saporiti, proprio come dovrebbero essere.",
                'user_name' => "PastaLover",
                'email' => "pastalover@example.com",
            ],
            [
                'review_title' => "Lasagna casalinga fantastica",
                'review' => "La lasagna sembrava fatta in casa, con strati di pasta morbida e un ragù delizioso. Davvero eccellente.",
                'user_name' => "LasagnaFan",
                'email' => "lasagnafan@example.com",
            ],
            [
                'review_title' => "Troppo rumore",
                'review' => "Il ristorante era troppo rumoroso, non riuscivamo a sentire nemmeno la conversazione al nostro tavolo.",
                'user_name' => "NoiseSensitive",
                'email' => "noisesensitive@example.com",
            ],
            [
                'review_title' => "Tortellini in brodo deliziosi",
                'review' => "I tortellini in brodo erano un vero comfort food. Il brodo era saporito e i tortellini erano ripieni alla perfezione.",
                'user_name' => "ComfortFoodFan",
                'email' => "comfortfoodfan@example.com",
            ],
            [
                'review_title' => "Riso venere con gamberi eccellente",
                'review' => "Un piatto leggero ma pieno di sapore. Il riso venere con gamberi era un'ottima scelta.",
                'user_name' => "SeafoodCritic",
                'email' => "seafoodcritic@example.com",
            ],
            [
                'review_title' => "Ottimo per una cena di lavoro",
                'review' => "Il locale è elegante e il servizio discreto, perfetto per una cena di lavoro. Il cibo era ottimo.",
                'user_name' => "BusinessDiner",
                'email' => "businessdiner@example.com",
            ],
            [
                'review_title' => "Cibo buono, ma troppo caro",
                'review' => "Il cibo era di qualità, ma i prezzi erano davvero esagerati rispetto alla quantità e al servizio.",
                'user_name' => "PriceCritic",
                'email' => "pricecritic@example.com",
            ],
            [
                'review_title' => "Cucina creativa e gustosa",
                'review' => "La creatività dei piatti mi ha colpito. Ogni portata era una sorpresa di sapori.",
                'user_name' => "CreativeDiner",
                'email' => "creativediner@example.com",
            ],
            [
                'review_title' => "Caffè freddo",
                'review' => "Mi hanno servito il caffè freddo e ho dovuto chiederlo di nuovo. Peccato, perché il resto era buono.",
                'user_name' => "CoffeeCritic",
                'email' => "coffeecritic@example.com",
            ],
            [
                'review_title' => "Esperienza nella media",
                'review' => "Non c'è stato nulla di speciale durante la cena. Il cibo era buono, ma non memorabile.",
                'user_name' => "AverageDiner",
                'email' => "averagediner@example.com",
            ],
            [
                'review_title' => "Menu degustazione eccellente",
                'review' => "Il menu degustazione è stata un'esperienza da ricordare. Ogni portata era curata e deliziosa.",
                'user_name' => "TastingMenuFan",
                'email' => "tastingmenufan@example.com",
            ],
            [
                'review_title' => "Non consigliato per i bambini",
                'review' => "Non c'erano molte opzioni adatte ai bambini. Il ristorante sembra più per adulti.",
                'user_name' => "FamilyDiner",
                'email' => "familydiner@example.com",
            ],
            [
                'review_title' => "Troppe spezie",
                'review' => "Il piatto era coperto da troppe spezie, il che copriva il sapore degli ingredienti.",
                'user_name' => "SpiceCritic",
                'email' => "spicecritic@example.com",
            ],
            [
                'review_title' => "Formaggi eccezionali",
                'review' => "La selezione di formaggi era ampia e di alta qualità. Ho apprezzato ogni assaggio.",
                'user_name' => "CheeseLover",
                'email' => "cheeselover@example.com",
            ],
            [
                'review_title' => "Cena romantica perfetta",
                'review' => "La cena è stata perfetta per una serata romantica. L'atmosfera e il cibo erano impeccabili.",
                'user_name' => "RomanticEater",
                'email' => "romanticeater@example.com",
            ],
            [
                'review_title' => "Piatto vegetariano delizioso",
                'review' => "Come vegetariano, è raro trovare un piatto così gustoso e ben preparato. Consigliatissimo.",
                'user_name' => "VeggieLover",
                'email' => "veggielover@example.com",
            ],
            [
                'review_title' => "Piatti troppo sofisticati",
                'review' => "Avrei preferito qualcosa di più semplice. I piatti erano troppo sofisticati per i miei gusti.",
                'user_name' => "SimpleEater",
                'email' => "simpleeater@example.com",
            ],
            [
                'review_title' => "Vino della casa eccellente",
                'review' => "Il vino della casa era sorprendentemente buono. Lo consiglio vivamente a chi visita il ristorante.",
                'user_name' => "WineConnoisseur",
                'email' => "wineconnoisseur@example.com",
            ],
            [
                'review_title' => "Piatto piccante perfetto",
                'review' => "Amo i piatti piccanti e questo era esattamente come lo desideravo, equilibrato e saporito.",
                'user_name' => "SpicyFan",
                'email' => "spicyfan@example.com",
            ],
            [
                'review_title' => "Menu troppo limitato",
                'review' => "Il menu era troppo limitato e non c'erano molte opzioni tra cui scegliere.",
                'user_name' => "LimitedOptions",
                'email' => "limitedoptions@example.com",
            ],
            [
                'review_title' => "Pane fatto in casa buonissimo",
                'review' => "Il pane fatto in casa era soffice e fragrante. Un ottimo inizio per la cena.",
                'user_name' => "BreadFanatic",
                'email' => "breadfanatic@example.com",
            ],
            [
                'review_title' => "Ottimi piatti senza glutine",
                'review' => "Finalmente un ristorante che offre ottime opzioni senza glutine. Sono rimasto soddisfatto.",
                'user_name' => "GlutenFreeEater",
                'email' => "glutenfreeeater@example.com",
            ],
            [
                'review_title' => "Ottimo per cene di gruppo",
                'review' => "Abbiamo cenato in gruppo e il servizio è stato rapido e il cibo di qualità. Lo consiglio.",
                'user_name' => "GroupDiner",
                'email' => "groupdiner@example.com",
            ],
            [
                'review_title' => "Gnocchi di patate spettacolari",
                'review' => "Gli gnocchi erano soffici e leggeri, un piatto davvero ben fatto.",
                'user_name' => "PotatoFan",
                'email' => "potatofan@example.com",
            ],
            [
                'review_title' => "Ambiente troppo formale",
                'review' => "Mi aspettavo un ambiente più rilassato, ma era tutto molto formale. Il cibo però era buono.",
                'user_name' => "CasualDiner",
                'email' => "casualdiner@example.com",
            ],
            [
                'review_title' => "Ottimi antipasti",
                'review' => "Gli antipasti erano eccellenti, soprattutto la burrata e i crostini con pomodorini.",
                'user_name' => "StarterLover",
                'email' => "starterlover@example.com",
            ],
            [
                'review_title' => "Pasta ripiena fenomenale",
                'review' => "La pasta ripiena era cotta alla perfezione, con un ripieno saporito e abbondante.",
                'user_name' => "PastaFanatic",
                'email' => "pastafanatic@example.com",
            ],
            [
                'review_title' => "Ottimi piatti di pesce",
                'review' => "Il pesce era freschissimo e cucinato alla perfezione. Da provare assolutamente.",
                'user_name' => "FishLover",
                'email' => "fishlover@example.com",
            ],
            [
                'review_title' => "Sapori unici",
                'review' => "Ogni piatto aveva una combinazione di sapori unica e sorprendente. Ottima cucina.",
                'user_name' => "TasteExplorer",
                'email' => "tasteexplorer@example.com",
            ],
            [
                'review_title' => "Pizza croccante e leggera",
                'review' => "La pizza era croccante ma leggera, con un impasto soffice e ben lievitato.",
                'user_name' => "PizzaCritic",
                'email' => "pizzacritic@example.com",
            ],
            [
                'review_title' => "Piatto del giorno eccellente",
                'review' => "Il piatto del giorno era un'ottima sorpresa. Sapori ben bilanciati e freschi.",
                'user_name' => "DailySpecialFan",
                'email' => "dailyspecialfan@example.com",
            ],
            [
                'review_title' => "Non male, ma non eccellente",
                'review' => "Il cibo era buono, ma non memorabile. Ho mangiato meglio altrove.",
                'user_name' => "FineDiner",
                'email' => "finediner@example.com",
            ],
            [
                'review_title' => "Dolci creativi",
                'review' => "I dolci erano veramente creativi e ben presentati. Un finale perfetto per la cena.",
                'user_name' => "SweetFinale",
                'email' => "sweetfinale@example.com",
            ],
            [
                'review_title' => "Atmosfera accogliente",
                'review' => "Il ristorante è piccolo ma accogliente. Ci siamo sentiti subito a casa.",
                'user_name' => "HomeyEater",
                'email' => "homeyeater@example.com",
            ],
            [
                'review_title' => "Non adatto ai bambini",
                'review' => "Il menù non aveva molte opzioni per i bambini. Un po' deludente per una cena in famiglia.",
                'user_name' => "FamilyCritic",
                'email' => "familycritic@example.com",
            ],
            [
                'review_title' => "Spaghetti aglio e olio perfetti",
                'review' => "Gli spaghetti aglio e olio erano semplici ma deliziosi. Cottura perfetta e ben equilibrati nei sapori.",
                'user_name' => "SimpleTaste",
                'email' => "simpletaste@example.com",
            ],
            [
                'review_title' => "Cacio e pepe ben eseguito",
                'review' => "Un piatto tradizionale eseguito alla perfezione. Cremoso, saporito e ben pepato.",
                'user_name' => "PastaFan88",
                'email' => "pastafan88@example.com",
            ],
            [
                'review_title' => "Gnocchi al tartufo eccezionali",
                'review' => "Gli gnocchi al tartufo erano un'esplosione di sapori. Il tartufo era ben bilanciato e non troppo invadente.",
                'user_name' => "TruffleLover",
                'email' => "trufflelover@example.com",
            ],
            [
                'review_title' => "Servizio impeccabile e cordiale",
                'review' => "Il servizio è stato cordiale e puntuale. Mi sono sentito davvero ben accolto e coccolato.",
                'user_name' => "ServiceCritic",
                'email' => "servicecritic@example.com",
            ],
            [
                'review_title' => "Antipasti deliziosi ma porzioni piccole",
                'review' => "Gli antipasti erano deliziosi, ma le porzioni erano piuttosto piccole per il prezzo.",
                'user_name' => "StarterCritic",
                'email' => "startercritic@example.com",
            ],
            [
                'review_title' => "Risotto troppo cotto",
                'review' => "Il risotto era troppo cotto e privo della classica consistenza cremosa. Peccato, perché il sapore era buono.",
                'user_name' => "RiceFan",
                'email' => "ricefan@example.com",
            ],
            [
                'review_title' => "Pesce al forno ottimo",
                'review' => "Il pesce al forno era fresco e ben cucinato. Una scelta eccellente per gli amanti del pesce.",
                'user_name' => "FishCritic",
                'email' => "fishcritic@example.com",
            ],
            [
                'review_title' => "Salse troppo salate",
                'review' => "Le salse erano eccessivamente salate e coprivano il sapore degli altri ingredienti.",
                'user_name' => "SaltSensitive",
                'email' => "saltsensitive@example.com",
            ],
            [
                'review_title' => "Ottima birra artigianale",
                'review' => "La birra artigianale era fresca e ben bilanciata. Una piacevole sorpresa nel menu.",
                'user_name' => "BeerLover",
                'email' => "beerlover@example.com",
            ],
            [
                'review_title' => "Tartare di manzo eccellente",
                'review' => "La tartare di manzo era deliziosa, con ingredienti freschi e un sapore intenso. Assolutamente da provare.",
                'user_name' => "MeatLover",
                'email' => "meatlover@example.com",
            ],
            [
                'review_title' => "Troppi piatti sul menu",
                'review' => "Il menu aveva troppe opzioni e risultava un po' dispersivo. Sarebbe meglio concentrarsi su meno piatti.",
                'user_name' => "MenuCritic",
                'email' => "menucritic@example.com",
            ],
            [
                'review_title' => "Panna cotta perfetta",
                'review' => "La panna cotta era liscia, cremosa e con la giusta consistenza. Un dessert perfetto.",
                'user_name' => "DessertLover99",
                'email' => "dessertlover99@example.com",
            ],
            [
                'review_title' => "Bevande troppo care",
                'review' => "Le bevande erano eccessivamente care rispetto ai piatti. Un punto negativo in un'esperienza complessivamente buona.",
                'user_name' => "DrinkCritic",
                'email' => "drinkcritic@example.com",
            ],
            [
                'review_title' => "Polenta perfetta per l'inverno",
                'review' => "La polenta era calda, cremosa e confortante, perfetta per una fredda serata invernale.",
                'user_name' => "WinterComfort",
                'email' => "wintercomfort@example.com",
            ],
            [
                'review_title' => "Cena perfetta con vista",
                'review' => "Abbiamo cenato con una splendida vista. Il cibo era eccellente e l'atmosfera ancora meglio.",
                'user_name' => "ViewLover",
                'email' => "viewlover@example.com",
            ],
            [
                'review_title' => "Fritto misto di mare troppo unto",
                'review' => "Il fritto misto era troppo unto e pesante. Avrei preferito una frittura più leggera.",
                'user_name' => "SeafoodFanatic",
                'email' => "seafoodfanatic@example.com",
            ],
            [
                'review_title' => "Menu senza opzioni vegetariane",
                'review' => "Il menu non aveva molte opzioni vegetariane, e quelle disponibili non erano molto creative.",
                'user_name' => "VeggieCritic",
                'email' => "veggiecritic@example.com",
            ],
            [
                'review_title' => "Pizza romana autentica",
                'review' => "La pizza romana era autentica, sottile e croccante come deve essere. La consiglio a tutti.",
                'user_name' => "PizzaFan77",
                'email' => "pizzafan77@example.com",
            ],
            [
                'review_title' => "Ottimi piatti di carne",
                'review' => "I piatti a base di carne erano eccezionali, con cottura perfetta e sapori ricchi. Consigliatissimo.",
                'user_name' => "MeatLover77",
                'email' => "meatlover77@example.com",
            ],
            [
                'review_title' => "Personale poco disponibile",
                'review' => "Il personale non sembrava molto interessato a prendersi cura dei clienti. Una nota negativa in un buon ristorante.",
                'user_name' => "CustomerServiceMatters",
                'email' => "customerservicematters@example.com",
            ],
            [
                'review_title' => "Ottima scelta di antipasti",
                'review' => "Gli antipasti erano vari e ben preparati, un ottimo inizio per la cena.",
                'user_name' => "StarterLover88",
                'email' => "starterlover88@example.com",
            ],
            [
                'review_title' => "Piatto troppo semplice",
                'review' => "Il piatto era troppo semplice per il prezzo richiesto. Mi aspettavo qualcosa di più elaborato.",
                'user_name' => "SimpleCritic",
                'email' => "simplecritic@example.com",
            ],
            [
                'review_title' => "Dolci fatti in casa favolosi",
                'review' => "I dolci fatti in casa erano favolosi, soprattutto la torta di mele calda servita con gelato.",
                'user_name' => "SweetTooth101",
                'email' => "sweettooth101@example.com",
            ],
            [
                'review_title' => "Servizio rapido e cortese",
                'review' => "Il servizio è stato rapido e cortese. Non abbiamo mai dovuto aspettare troppo per nessuna portata.",
                'user_name' => "FastServiceFan",
                'email' => "fastservicefan@example.com",
            ],
            [
                'review_title' => "Ambiente informale e piacevole",
                'review' => "L'ambiente era informale e piacevole, perfetto per una cena tra amici.",
                'user_name' => "CasualDiner77",
                'email' => "casualdiner77@example.com",
            ],
            [
                'review_title' => "Pasta fatta in casa ottima",
                'review' => "La pasta fatta in casa era ottima, con una consistenza perfetta. Si sentiva che era fresca.",
                'user_name' => "PastaCritic77",
                'email' => "pastacritic77@example.com",
            ],
            [
                'review_title' => "Servizio lento e disorganizzato",
                'review' => "Il servizio è stato lento e disorganizzato. Anche se il cibo era buono, l'esperienza non è stata piacevole.",
                'user_name' => "SlowServiceCritic",
                'email' => "slowservicecritic@example.com",
            ],
            [
                'review_title' => "Troppo formale per i miei gusti",
                'review' => "Il ristorante era troppo formale per i miei gusti, mi aspettavo qualcosa di più rilassato.",
                'user_name' => "CasualFan",
                'email' => "casualfan@example.com",
            ],
            [
                'review_title' => "Mousse al cioccolato irresistibile",
                'review' => "La mousse al cioccolato era leggera e irresistibile, il miglior dessert della serata.",
                'user_name' => "ChocoLover88",
                'email' => "chocolover88@example.com",
            ],
            [
                'review_title' => "Pane servito freddo",
                'review' => "Il pane servito al tavolo era freddo e non molto invitante. Mi aspettavo di più.",
                'user_name' => "BreadCritic",
                'email' => "breadcritic@example.com",
            ],
            [
                'review_title' => "Ottimo per una cena di gruppo",
                'review' => "Il ristorante è perfetto per cene di gruppo, con grandi tavoli e porzioni abbondanti.",
                'user_name' => "GroupEater",
                'email' => "groupeater@example.com",
            ],
            [
                'review_title' => "Dolci da sogno",
                'review' => "I dolci erano da sogno. Ogni morso era una delizia. Consiglio vivamente il tiramisù.",
                'user_name' => "DessertDreamer",
                'email' => "dessertdreamer@example.com",
            ],
            [
                'review_title' => "Troppo caro per quello che offre",
                'review' => "Il ristorante è troppo caro per quello che offre. Il cibo è buono, ma non giustifica il prezzo.",
                'user_name' => "ValueSeeker",
                'email' => "valueseeker@example.com",
            ],
            [
                'review_title' => "Tavoli troppo vicini",
                'review' => "I tavoli erano troppo vicini e il ristorante risultava rumoroso e poco confortevole.",
                'user_name' => "SpaceCritic",
                'email' => "spacecritic@example.com",
            ],
            [
                'review_title' => "Polpette perfette",
                'review' => "Le polpette erano saporite e tenere, proprio come quelle fatte in casa. Le consiglio vivamente.",
                'user_name' => "MeatballLover",
                'email' => "meatballlover@example.com",
            ],
            [
                'review_title' => "Portate troppo piccole",
                'review' => "Le portate erano troppo piccole e non sono riuscito a saziarmi nonostante il prezzo alto.",
                'user_name' => "SmallPlateCritic",
                'email' => "smallplatecritic@example.com",
            ],
            [
                'review_title' => "Piatto freddo e insipido",
                'review' => "Il mio piatto è stato servito freddo e privo di sapore. Purtroppo, è stata un'esperienza deludente.",
                'user_name' => "ColdFoodCritic",
                'email' => "coldfoodcritic@example.com",
            ],
            [
                'review_title' => "Cena elegante e raffinata",
                'review' => "L'esperienza culinaria è stata elegante e raffinata. Ogni piatto era curato nei minimi dettagli.",
                'user_name' => "ElegantDiner",
                'email' => "elegantdiner@example.com",
            ],
            [
                'review_title' => "Ottima selezione di formaggi",
                'review' => "La selezione di formaggi era vasta e ben assortita. Ogni formaggio aveva un sapore unico.",
                'user_name' => "CheeseFan",
                'email' => "cheesefan@example.com",
            ],
            [
                'review_title' => "Piatto del giorno deludente",
                'review' => "Il piatto del giorno non ha soddisfatto le aspettative. Era troppo semplice e privo di sapore.",
                'user_name' => "DailySpecialCritic",
                'email' => "dailyspecialcritic@example.com",
            ],
            [
                'review_title' => "Ottimo vino locale",
                'review' => "Il vino locale era eccellente, ben bilanciato e perfetto in abbinamento con il cibo.",
                'user_name' => "WineFan77",
                'email' => "winefan77@example.com",
            ],
            [
                'review_title' => "Tavolo vicino alla cucina troppo rumoroso",
                'review' => "Eravamo seduti vicino alla cucina e il rumore ci ha disturbato per tutta la cena.",
                'user_name' => "NoiseCritic",
                'email' => "noisecritic@example.com",
            ],
            [
                'review_title' => "Sorpresa culinaria",
                'review' => "Non mi aspettavo una cucina così buona. Ogni piatto è stato una piacevole sorpresa.",
                'user_name' => "HappyDiner88",
                'email' => "happydiner88@example.com",
            ],
            [
                'review_title' => "Cena mediocre",
                'review' => "La cena è stata mediocre, senza nulla di speciale. Ci sono posti migliori in città.",
                'user_name' => "FineCritic",
                'email' => "finecritic@example.com",
            ],
            [
                'review_title' => "Ambiente rustico e accogliente",
                'review' => "L'ambiente rustico e accogliente rende il locale perfetto per una cena informale. Il cibo era buono.",
                'user_name' => "RusticLover",
                'email' => "rusticlover@example.com",
            ],
            [
                'review_title' => "Piatto piccante ben equilibrato",
                'review' => "Il piatto piccante era perfettamente bilanciato. La giusta dose di spezie senza coprire i sapori.",
                'user_name' => "SpicyLover",
                'email' => "spicylove@example.com",
            ],
            [
                'review_title' => "Troppo caro per la qualità",
                'review' => "Il prezzo era troppo alto per la qualità del cibo. Ci sono opzioni migliori in zona.",
                'user_name' => "PriceCritic88",
                'email' => "pricecritic88@example.com",
            ],
            [
                'review_title' => "Esperienza culinaria perfetta",
                'review' => "Dall'inizio alla fine, tutto era perfetto. Ogni piatto era un'esperienza culinaria.",
                'user_name' => "GourmetLover",
                'email' => "gourmetlover@example.com",
            ],
        ];

        $chefs = Chef::all()->pluck('id');
        foreach ($reviews as $review) {
            $review['chef_id'] = $faker->randomElement($chefs);
            Review::create($review);
        }
    }
}
